import 'server-only';
import type { PublicQuestion, Topic } from '@/lib/questions';
interface EditorialQuestion extends PublicQuestion { criteria:string[]; alternatives:string[]; pitfalls:string[]; }
const rows: [string,Topic,string,string,string[],string[],string[],string[]][]=[
 ['js-closures','JavaScript','Closures in everyday code','How can a callback still use a variable after its outer function has returned? Give a practical example.', ['js-closures'], ['A function retains access to bindings in its lexical environment.','The retained binding is not necessarily a frozen value.'],['A factory function, event handler or private counter is a valid example.'],['Do not claim that closures copy all captured values at creation.']],
 ['js-async','JavaScript','The order of async work','Why does a promise callback run after synchronous code, even when the promise is already resolved?', ['js-promises'],['Promise handlers are scheduled rather than called inline.','Synchronous execution completes before queued promise reactions run.'],['An example with logging is enough; terminology alone is not required.'],['Do not confuse a promise reaction with a timer task.']],
 ['js-copy','JavaScript','Copying without surprises','You copy an object with spread and change a nested property. Why might the original change, and how would you avoid it?', ['js-copy'],['Object spread makes a shallow copy; nested objects can still be shared.','Copy the modified nesting path or use a suitable deep-copy strategy.'],['structuredClone is acceptable when the data types are supported.'],['Do not present JSON round-tripping as a universal clone.']],
 ['js-errors','JavaScript','When one request fails','Two independent requests run through Promise.all. One rejects. What happens, and what would you change if partial results are useful?', ['js-all','js-promises'],['The combined promise rejects when an input rejects; other work is not automatically cancelled.','Handle failure deliberately; allSettled is useful when every outcome matters.'],['Per-request error handling can also preserve partial results.'],['Do not claim Promise.all cancels the remaining operations.']],
 ['ts-narrowing','TypeScript','Working safely with unknown','An API returns unknown. How do you safely read a property from that value?', ['ts-narrowing','ts-runtime'],['Narrow with runtime checks before property access.','Type assertions alone do not validate data.'],['Schema validation or a correctly implemented type guard are acceptable.'],['Do not treat as as a runtime conversion.']],
 ['ts-unions','TypeScript','Make impossible states harder','How would you model loading, success and failure so that data is available only in the success case?', ['ts-narrowing'],['Use a discriminated union with a literal status for each variant.','A status check narrows which fields are available; exhaustive handling can use never.'],['A simple branching example is sufficient.'],['Independent optional data and error fields allow inconsistent combinations.']],
 ['ts-generics','TypeScript','Why use a generic?','How does a generic identity function differ from one that accepts and returns any?', ['ts-generics'],['A generic preserves a relationship between input and output types.','any discards checking and the useful relationship.'],['An array helper or constrained generic can illustrate the same principle.'],['Generics do not supply runtime validation.']],
 ['ts-runtime','TypeScript','Trusting external data','Your response is asserted as User, but the server returns a different shape. What protection does TypeScript give at runtime?', ['ts-runtime'],['Type assertions are removed and do not check external values at runtime.','Validate at the boundary and handle validation failure.'],['A schema library or explicit runtime checks are both valid.'],['A successful compilation is not evidence of a valid server response.']],
 ['react-state','React','A snapshot, not a variable','You call setCount(count + 1) three times in one click handler. Why may the count increase only once?', ['react-state'],['The handler reads the state snapshot from its render.','Functional updater calls can express successive changes based on queued state.'],['Explain the values passed to the setter with a small example.'],['Do not describe the setter as mutating the local count variable.']],
 ['react-keys','React','Identity in a changing list','An editable list is reordered and inputs appear attached to the wrong item. How could keys cause this?', ['react-keys'],['Keys help React match identity within a parent.','Index keys can associate preserved state with the wrong item after reordering.'],['Stable item identifiers and avoiding regenerated random keys are valid remedies.'],['Keys are not globally unique identifiers across the entire application.']],
 ['react-effects','React','When an Effect is unnecessary','A component stores a filtered list in state and updates it in an Effect. How would you approach this?', ['react-effects'],['Derive the filtered list from current inputs during render when no external system is involved.','Consider memoization only when calculation cost justifies it.'],['A measured expensive computation may justify useMemo.'],['Do not use an Effect merely to keep two representations of the same data synchronized.']],
 ['react-fetch','React','Responses arriving out of order','A user switches search terms quickly. An older request finishes last and replaces newer results. How would you prevent this?', ['react-fetch'],['Ignore stale results using cleanup or a request identity.','Abort when possible, while ensuring only the active request can update state.'],['A data-fetching library with correct request-key handling is also acceptable.'],['Cleanup should protect against stale updates, not just remove a loading indicator.']],
];
export const questions:EditorialQuestion[]=rows.map(([id,topic,title,question,sourceIds,criteria,alternatives,pitfalls])=>({id,version:1,topic,title,question,sourceIds,criteria,alternatives,pitfalls}));
export function publicQuestions():PublicQuestion[]{return questions.map(({id,version,topic,title,question,sourceIds})=>({id,version,topic,title,question,sourceIds}));}
export function findQuestion(id:string,version:number){return questions.find(q=>q.id===id&&q.version===version);}
